version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/server-dev.dockerfile
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - /app/node_modules
      - ./cordova/www:/app/cordova/www
      - ./back:/app/back
    env_file:
      - ./env/server.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - ./env/mongodb.env
    ports:
      - "27017"
    volumes:
      - database:/data/db
volumes:
  database: { }
